.github/CODEOWNERS
Added **Ivan** as codeowner for the **test** and the **Expenses** directory.
=> added codeowner for expenses and test

.github/CODEOWNERS
Added Edwin as codeowner for the signup, login and routing.
Added package.json codeowner for the dependencies.
=> added codeowner for package json dependencies and routing

src/components/Header/HeaderComponents/BasicMenu.jsx
Navbar logout function updated
=> Navbar logout function

.env, src/pages/EmiCalculator/index.jsx, src/provider/Provider.js
For the physical assets there were some dependency was there with .env file. so resolved that.
=> removed .env dependency for the app

CONTRIBUTING.md, README.md
added some guidelines to contribute in the project as we proceed we will add more and update this.
=> updated the contribute file

.github/workflows/deploy_ec2.yml, .github/workflows/deploy_s3.yml
adds deploy_ec2 script to deploy to ec2 pm2 server
=> renames deploy.yml to deploy_s3

package-lock.json, package.json, src/index.tsx
=> feat: added google analytics

src/App.tsx, src/hooks/use-auth.ts, src/pages/BalanceSheet/components/AddOrEditAssetDialog.tsx, src/pages/BalanceSheet/components/AddOrEditLiabilityDialog.tsx, src/pages/BalanceSheet/components/DeleteAssetDialog.tsx, src/pages/BalanceSheet/components/DeleteLiabilityDialog.tsx, src/pages/Expenses/components/AddOrEditExpenseDialog/AddOrEditExpenseDialog.tsx, src/pages/Expenses/components/DeleteExpense.tsx, src/pages/Expenses/components/EditBudgetModal.tsx, src/pages/Expenses/components/SetBudgetModal.tsx, src/pages/Expenses/components/ViewAllBudgetModal.tsx, src/pages/Goals/components/AddOrEditGoal.tsx, src/pages/Goals/components/DeleteGoal.tsx, src/pages/IncomeStatement/components/AddOrEditIncomeExpense.tsx, src/pages/IncomeStatement/components/DeleteIncomeStatement.tsx, src/utils/utils.ts
I've implemented a utility function for managing errors, capable of handling errors associated with all status codes. 
Additionally, I've integrated this function into all mutations across our website.
- This will fix this #343 issue
=> perf: :bulb: Handling errors for API error messages

package-lock.json, package.json, src/components/Charts/BudgetChart.tsx, src/components/ui/progress.tsx, src/pages/Dashboard/Dashboard.tsx
- I have added card view which shows expense and budget remaining
- 🟢  color is used if expense usages is less than 80%
- 🟡  color is used if expense usages is more than 95%
- 🔴  color is used if expense usages is more than 100%
- #245
=> feat: :art: Added a card view for budget at home screen

src/App.tsx, src/components/CookieConsent/CookieConsent.tsx, src/hooks/use-auth.ts, src/utils/constants.ts
- Added Cookie Consent Popup for New User #281 
- ![image](https://github.com/GVR-Secure-Solutions/lekkalu-frontend/assets/87645745/0604f96b-3cdb-4751-876c-54533a4c73ee)
=> feat: :label: Added Cookie Consent Popup for New User

src/queries/feedback.ts, src/utils/client.ts
fix: added one apiClient without interceptors feedback form fix
=> fix: added one apiClient without interceptors feedback form fix

.github/CODEOWNERS, src/components/DatePicker/DatePicker.tsx, src/components/ui/calendar.tsx, src/styles/globals.css
=> feat: added calender MM YYYY dropdown

src/queries/auth.ts
changed users in prod from /users/api/users to /users/api/users_1
=> updated the endpoint for the user creation

src/components/DatePicker/DatePicker.tsx, src/pages/Expenses/components/AddOrEditExpenseDialog/AddOrEditExpenseDialog.tsx, src/pages/Expenses/components/EditBudgetModal.tsx, src/pages/Expenses/components/SetBudgetModal.tsx, src/pages/IncomeStatement/components/AddOrEditIncomeExpense.tsx, src/pages/IncomeStatement/components/IncomeExpenseTable.tsx, src/pages/Settings/Settings.tsx
added toFixed method to handle decimals part in the frontend.
=> fix : added decimal minimum length

package-lock.json, package.json
Reverts GVR-Secure-Solutions/lekkalu-frontend#451
=> Revert "build(deps): bump @tanstack/react-query from 4.36.1 to 5.21.4"

environments/.prod.env, package-lock.json, src/components/SocialAuth/GoogleAuth.tsx, src/hooks/use-auth.ts, src/pages/Home/Home.tsx, src/pages/Signin/Signin.tsx, src/pages/Signup/Signup.tsx, src/queries/auth.ts, src/utils/client.ts
User can Login and Signup Using Google
#28
=> feat: :lock: login and signup using google

src/pages/Comparison/ComparisonDetail.tsx
This PR fixes all scenarios not displaying in graph issue.
Related to issue #515.
=> Show all scenarios in comparison graph.

src/components/Charts/BudgetChart.tsx, src/pages/BalanceSheet/components/AssetsTable.tsx, src/pages/BalanceSheet/components/LiabilitiesTable.tsx, src/pages/CAGRCalculator/CAGRCalculator.tsx, src/pages/EmailVerification/EmailVerification.test.tsx, src/pages/EmiCalculator/EmiCalculator.tsx, src/pages/Expenses/components/ExpensesTable.tsx, src/pages/Expenses/components/ViewAllBudgetModal.tsx, src/pages/GoalDetails/GoalDetails.tsx, src/pages/IncomeStatement/components/IncomeExpenseTable.tsx, src/pages/SIPCalculator/SIPCalculator.tsx, src/pages/Scenarios/components/Assets/EachAsset.tsx, src/pages/Scenarios/components/IncomeExpenses/EachExpense.tsx, src/pages/Scenarios/components/Liability/EachLiabilityForScenario.tsx, src/utils/format-money.ts
- Issue:- #352 
- I have added utils function for convert number into indian notation like (K, Lacs, Cr)
=> fix: indian money notation added

src/components/Charts/BudgetChart.tsx, src/components/Charts/WeeklyChart.tsx
=> fix: added year check along with month check

src/pages/IncomeStatement/components/AddOrEditIncomeExpense.tsx
This PR is related to issue #448.
=> Fix: Display proper error message in income-expense

environments/.prod.env
@bharathkumarchowdary I've updated API's base URL
=> perf: :rocket: updated api's base url

src/components/NotificationPopover/NotificationPopover.tsx
=> Notification Count Badge

src/App.tsx, src/components/AppShell/AppShell.tsx, src/components/AppShell/components/NavLink.tsx, src/components/AppShell/components/Sidebar.tsx, src/components/Page/Page.tsx, src/components/UnAuthenticatedHeader/UnAuthenticatedHeader.tsx, src/hooks/use-auth.ts, src/pages/Expenses/Expenses.tsx, src/pages/Lending/Lending.tsx, src/pages/Settings/Settings.tsx, src/styles/globals.css, tailwind.config.js
Uploading sidebar_responsive.mov…
#519
=> fix: sidebar repsonsivness

src/components/AppShell/AppShell.tsx
Users now only see the profile tab out the profile page #551
=> Removed profile tab from profile page

src/schema/auth.ts
=> User have to accept the privacy & terms & conditions for signup

src/pages/Lending/components/AddOrEditTransaction/AddOrEditTransaction.tsx
=> 🐛 Fix:Borrowed entry edit shows negative value

package-lock.json
=> perf: :fire: React Query Upgraded to latest version

src/components/DetailPageHeading/index.tsx, src/pages/Comparison/ComparisonDetail.tsx, src/pages/Comparison/components/Scenario/EachScenarioInComparison.tsx, src/pages/Scenarios/components/Assets/AddOrEditAssetsForScenarios.tsx, src/pages/Scenarios/components/CreateButton.tsx, src/pages/Scenarios/components/IncomeExpenses/EachExpense.tsx, src/pages/Scenarios/components/IncomeExpenses/index.tsx, src/pages/Scenarios/components/Liability/AddorEditLiabilityDialog.tsx, src/queries/auth.ts, src/schema/balance-sheet.ts, src/schema/income-statement.ts, src/styles/globals.css
This PR is associated with issue #522.
=> Fix: Depreciation by year issue in asset

src/components/AppShell/components/Sidebar.tsx
=> Make sidebar scrollable.

src/components/InputFieldsRenderer/InputFieldsRenderer.tsx, src/pages/Comparison/components/EachComparison.tsx, src/pages/Comparison/components/EachComparisonOptions.tsx, src/pages/Comparison/index.tsx, src/pages/Scenarios/AddScenario.tsx, src/pages/Scenarios/EditScenario.tsx, src/pages/Scenarios/ScenarioDetail.tsx, src/pages/Scenarios/components/Assets/EachAsset.tsx, src/pages/Scenarios/components/CreateButton.tsx, src/pages/Scenarios/components/EachScenario.tsx, src/pages/Scenarios/components/EachScenarioOptions.tsx, src/pages/Scenarios/components/IncomeExpenses/EachExpense.tsx, src/pages/Scenarios/components/Liability/EachLiabilityForScenario.tsx, src/pages/Scenarios/components/ViewScenarioEntity.tsx
=> Scenario UI issues.

src/pages/GoalDetails/components/GoalTimeline.tsx
=> Add Toolbar in goal detail chart.

src/hooks/use-auth.ts
⚠️ This PR requires further discussion on Authentication logic.
=> Bug: Remove /refresh api call on logout

src/hooks/use-auth.ts
This PR addresses and should close issue #650.
=> Fix: Logout issue.

src/pages/EmailVerification/EmailVerification.tsx, src/pages/EmailVerification/EmailVerificationProcess.tsx, src/pages/Profile/Profile.tsx, src/schema/user.ts
This PR addresses and should close issues #648 and #649.
Task completed in this PR:
=> Fix: Email related issues
